theme: jekyll-theme-cayman
title: Music Community Lab
description: "Music Community Lab is the non-profit entity that organizes the Monthly Music Hackathon. This page details our mission and values."

donate_url: https://www.fracturedatlas.org/site/fiscal/profile?id=16959#giving_levels
volunteer_url: https://goo.gl/forms/4WZ56lDDrSozGxWb2
discuss_url: https://groups.google.com/forum/#!forum/mcl-discuss
